name: 'Axiom annotation'
author: 'Axiom, Inc.'
description: 'Create annotations in Axiom'

branding:
  icon: 'message-square'
  color: 'black'

inputs:
  axiomApiUrl:
    description: 'The Axiom API URL, defaults to https://api.axiom.co'
    required: false
    default: ''
  datasets:
    description: 'Comma separated list of datasets to associate the annotation with'
    required: true
  token:
    description: 'Axiom API token'
    required: true
  time:
    description: 'The time of the annotation (defaults to now)'
    required: false
    default: ''
  endTime:
    description: 'The end time of the annotation (if set, will create a ranged annotation)'
    required: false
    default: ''
  title:
    description: 'The title of the annotation'
    required: false
    default: ''
  description:
    description: 'The description of the annotation (supports Markdown)'
    required: false
    default: ''
  url:
    description: 'The URL to link to (defaults to the GitHub Actions run URL)'
    required: false
    default: ''
  type:
    description: 'The type of the annotation, (e.g. production-deploy)'
    required: true

outputs:
  id:
    description: 'The ID of the created integration'

runs:
  using: node20
  main: dist/index.js
