name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action (Minimal)
        id: test-action-minimal
        uses: ./
        with:
          axiomToken: ${{ secrets.AXIOM_TOKEN }}
          axiomUrl: ${{ secrets.AXIOM_API_URL }}
          datasets: annotations-action-ci
          type: "minimal-example"
      - name: Test Local Action (Complete)
        id: test-action-complete
        uses: ./
        with:
          axiomToken: ${{ secrets.AXIOM_TOKEN }}
          axiomUrl: ${{ secrets.AXIOM_API_URL }}
          datasets: annotations-action-ci
          type: "complete-example"
          time: "2024-01-01T00:00:00Z"
          endTime: "2024-01-01T01:00:00Z"
          title: "Complete example"
          description: "This annotation has all the fields!"
          url: "https://axiom.co"
      - name: "Install Hurl"
        run: |
          VERSION=4.3.0
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/$VERSION/hurl_${VERSION}_amd64.deb
          sudo apt update && sudo apt install ./hurl_${VERSION}_amd64.deb      
      - run: |
          hurl <<EOF
            GET ${{ secrets.AXIOM_API_URL }}/v2/annotations/${{ steps.test-action-minimal.outputs.id }}
            authorization: Bearer ${{ secrets.AXIOM_TOKEN }}
            HTTP 200
            [Asserts]
            jsonpath "$.id" == "${{ steps.test-action-minimal.outputs.id }}"
            jsonpath "$.type" == "minimal-example"
          EOF
      - run: |
          hurl <<EOF
            GET ${{ secrets.AXIOM_API_URL }}/v2/annotations/${{ steps.test-action-complete.outputs.id }}
            authorization: Bearer ${{ secrets.AXIOM_TOKEN }}
            HTTP 200
            [Asserts]
            jsonpath "$.id" == "${{ steps.test-action-complete.outputs.id }}"
            jsonpath "$.time" == "2024-01-01T00:00:00.000Z"
            jsonpath "$.endTime" == "2024-01-01T01:00:00.000Z"
            jsonpath "$.title" == "Complete example"
            jsonpath "$.description" == "This annotation has all the fields!"
            jsonpath "$.url" == "https://axiom.co"
            jsonpath "$.type" == "complete-example"
          EOF
